### ISSUE TITLE
Make pytest-runner conditional in setup.py

### ISSUE THREAD

**Issue by mikerahk** [Hugovdberg/PIconnect#503]
Bug report
==========

Description
-----------

A coworker experienced an error when trying to install `PIconnect` into her Anaconda environment, I experienced the same error when installing into a vanilla venv. 

To Reproduce
------------

Using Python 3.7.4 with the standard library:

```cmd
py -m venv venv
venv\Scripts\activate
pip install PIconnect
```

Error:
```
Collecting PIconnect
  Downloading https://files.pythonhosted.org/packages/63/29/714e87723fb8cbb4b21e6fdedcce34d4c28bdf6d37f4fe8a687c3bfb7289/PIconnect-0.7.1.tar.gz
    Complete output from command python setup.py egg_info:
    Download error on https://pypi.org/simple/pytest-runner/: [WinError 10054] An existing connection was forcibly closed by the remote host -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [WinError 10054] An existing connection was forcibly closed by the remote host -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\...\AppData\Local\Temp\pip-install-rq3lke40\PIconnect\setup.py", line 109, in <module>
        package_data={
      File "c:\users\...\desktop\test\venv\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\...\desktop\test\venv\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\...\desktop\test\venv\lib\site-packages\setuptools\dist.py", line 724, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\...\desktop\test\venv\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "c:\users\...\desktop\test\venv\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\users\...\desktop\test\venv\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\users\...\desktop\test\venv\lib\site-packages\setuptools\dist.py", line 791, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\...\desktop\test\venv\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\...\AppData\Local\Temp\pip-install-rq3lke40\PIconnect\
```

Expected behavior
-----------------

`PIconnect` and its dependencies are installed by `pip`.

Possible solutions
------------------

- install `pytest-runner` before installing `PIconnect`, this resolved the error
- make `pytest-runner` conditional for setup: 
    <https://github.com/pytest-dev/pytest-runner#conditional-requirement>

Screenshots
-----------

None.

System
------

|| Me | Coworker
--- | --- | ---
OS | Windows 10 | Windows 10
Python version | 3.7.4 | 2.7.x
PIconnect version | 0.7.1 | 0.7.1
Anaconda Dist. | - | 5.2.0

Additional context
------------------

https://github.com/Hugovdberg/PIconnect/blob/ec65edd4677007dd9dc372036440b63eb104ba8c/setup.py#L34
https://github.com/Hugovdberg/PIconnect/blob/ec65edd4677007dd9dc372036440b63eb104ba8c/setup.py#L78

**Comment by Hugovdberg** [comment]
Thanks for letting me know. I guess that dependency should either be part
of the test requirements, or be removed at all because I don't know for
sure why it's included. I'll look into this next week!

Op vr 10 jan. 2020 19:08 schreef mikerahk <notifications@github.com>:
