### ISSUE TITLE
PIAFDatabase error

### ISSUE THREAD

**Issue by aumanusorn** [Hugovdberg/PIconnect#568]
System.ComponentModel.Win32Exception: The logon attempt failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File ".\test_pi_4.py", line 1, in <module>
    import PIconnect as PI
  File "C:\Users\anusorbo\AppData\Local\Programs\Python\Python38\lib\site-packages\PIconnect\__init__.py", line 28, in <module>
    from PIconnect.PIAF import PIAFDatabase
  File "C:\Users\anusorbo\AppData\Local\Programs\Python\Python38\lib\site-packages\PIconnect\PIAF.py", line 61, in <module>
    class PIAFDatabase(object):
  File "C:\Users\anusorbo\AppData\Local\Programs\Python\Python38\lib\site-packages\PIconnect\PIAF.py", line 69, in PIAFDatabase
    servers = {
  File "C:\Users\anusorbo\AppData\Local\Programs\Python\Python38\lib\site-packages\PIconnect\PIAF.py", line 70, in <dictcomp>
    s.Name: {"server": s, "databases": {d.Name: d for d in s.Databases}}
  File "C:\Users\anusorbo\AppData\Local\Programs\Python\Python38\lib\site-packages\PIconnect\PIAF.py", line 70, in <dictcomp>
    s.Name: {"server": s, "databases": {d.Name: d for d in s.Databases}}
System.Security.Authentication.InvalidCredentialException: The server has rejected the client credentials.
   at System.Net.Security.NegoState.ProcessReceivedBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.StartSendBlob(Byte[] message, LazyAsyncResult lazyResult)
   at System.Net.Security.NegoState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.NegotiateStream.AuthenticateAsClient(NetworkCredential credential, String targetName, ProtectionLevel requiredProtectionLevel, TokenImpersonationLevel allowedImpersonationLevel)
   at System.ServiceModel.Channels.WindowsStreamSecurityUpgradeProvider.WindowsStreamSecurityUpgradeInitiator.OnInitiateUpgrade(Stream stream, SecurityMessageProperty& remoteSecurity)

**Comment by Hugovdberg** [comment]
This is probably related to the issue #562 tries to fix. However, it also appears you actually need to provide credentials to be able to connect to the server. Currently connecting to an AF database cannot take credentials. I would have to research whether this uses the same mechanism as the PI Data Archive, so we can reuse some of the previous work.
