### ISSUE TITLE
Was able to connect for a while, until the server was migrated.

### ISSUE THREAD

**Issue by Razmand1** [Hugovdberg/PIconnect#689]
Hallo,

I was able to connect to the PI server and had lots of fun with it, until they migrated the server and now I get this error code:

PIAuthenticationException: Cannot connect to the PI Data Archive. Windows authentication trial failed because the authentication method was not tried. Trust authentication trial failed because insufficient privilege to access the PI Data Archive. 
   at OSIsoft.AF.PI.PIException.ConvertAndThrowException(PIServer piServer, Exception ex, String message)
   at OSIsoft.AF.PI.PIServer.RemoteConnect(AFConnectionPreference preference, NetworkCredential credential, PIAuthenticationMode authenticationMode)
   at OSIsoft.AF.PI.PIServer.InternalConnect(Int32 numRetries, IWin32Window owner, AFConnectionPreference preference, NetworkCredential credential, PIAuthenticationMode authenticationMode, Boolean checkConnectingAsSameUser)
   at OSIsoft.AF.PI.PIServer.AutoConnect(Boolean allowDirectConnect, Boolean force)

I have tried a lot but the server administrators keep insisting that nothing has changed so i should be able to connect. I use the standard step by step guide to connect with the pi server and get time series data from data tags on the pi server. Can anyone help me with this please?

Kind regads,

Raz

**Comment by niltecedu** [comment]
This is a windows AD issue, see if your user has access to PI server

**Comment by Razmand1** [comment]
Hi Nilesh,

Thank you so much for the reaction. Yes, my windows account is connected to
pi, as per my excel I can get data from the tags I search using the pi data
builder. Also the pi data link tab shows my connection to the server and
the server name...


Thanks again

Op wo 1 feb. 2023 14:42 schreef Nilesh Zagade ***@***.***>:

**Comment by niltecedu** [comment]
hiya,

so we have a similar issue come up quite often. try reinstalling pisdk
since the windows account seems fine. seems like its trying to find it via
older ip

**Comment by Hugovdberg** [comment]
To me this sounds like there is some configuration issue on your computer. It is strange you can use PI Datalink, but not `PIconnect`, as they use the same DLL's and configuration to connect to the server as far as I`m aware. There is no configuration in `PIconnect` that keeps a reference to servers once the python process ends, everything is requested from the local configuration.

As I don't think this is an issue with this package, but a useful discussion, if only for documentation, I will convert this to a discussion instead of an issue.
