### ISSUE TITLE
Attribute Error: AFBufferOption, tried venv, also local download how fix?

### ISSUE THREAD

**Issue by arthurpalayer** [Hugovdberg/PIconnect#713]
Bug report
==========

Description
-----------
cannot import PIconnect, can connect to PI servers through PI process book, but not through python. No admin privileges. 

To Reproduce
------------
$python
>>import piconnect

Expected behavior
-----------------

Can connect to PI servers through Python and import data

Possible solutions
------------------
getting admin rights possibly? This same error occured when could not connect to PI Processbook, but can now connect to PI Processbook and no longer to PIconnect. 

Screenshots
-----------

OSIsoft(r) AF SDK Version: 2.5.2.5396
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\myusername\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIconnect\__init__.py", line 7, in <module>
    from PIconnect.PI import PIServer
  File "C:\Users\myusername\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIconnect\PI.py", line 8, in <module>
    import PIconnect.PIPoint as PIPoint_
  File "C:\Users\myusername\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIconnect\PIPoint.py", line 4, in <module>
    from PIconnect import AF, PIConsts, PIData, _time
  File "C:\Users\myusername\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIconnect\PIData.py", line 56, in <module>
    class PISeriesContainer(abc.ABC):
  File "C:\Users\myusername\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\PIconnect\PIData.py", line 595, in PISeriesContainer
    buffer_mode: AF.Data.AFBufferOption,
                 ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: AFBufferOption

System
------

-   OS: \Windows
-   Python version: 3.11 (also tested 2.9)
-   PIconnect version: most recent 0.10.6

**Comment by Hugovdberg** [comment]
This is an issue with different versions of the PI AF SDK, some newer
functionality is used in PIconnect that is not available in the installed
PI software on your computer. Is it possible to upgrade the SDK? I'm still
trying to figure out a way to support multiple versions of the SDK without
a lot of manual labour and without needing to support different versions of
PIconnect which everyone should select the version matching their software
from...

Op ma 17 jul. 2023 21:07 schreef arthurpalayer ***@***.***>:
